### ISSUE TITLE
ProtocolLib: Error When Players Join

### ISSUE THREAD

**Issue by 1Pootis1** [WolfyScript/CustomCrafting#153]
### What happened?

error when the player joined the server
![image](https://user-images.githubusercontent.com/73141732/181997178-ca25398c-ba9c-4f16-bccc-ac588a559970.png)

### How can the bug be reproduced?

1. start the server
2. log in
3. see console

### Expected Behaviour?

no errors

### Plugin version

customcrafting-spigot-3.16.6.2, wolfyutils-spigot-4.16.4.1

### Server software

Paper 1.18.1

### Relevant log output

```shell
https://pastebin.com/0CNcT2j4
```

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by BeepoWuff** [comment]
Hey there,

Thanks for reporting this.
We've had this error start to be reported by a few other users over on the discord as well. From our investigation it looks like the latest / 1.19 support dev build of ProtocolLib made some compatibility breaking changes to code that CustomCrafting utilises.

We are planning to implement changes to support the new ProtocolLib version but they are still pending at the moment. As a workaround and since you're still on 1.18 you should be fine to roll back to the older build of ProtocolLib for now to resolve the errors.

**Comment by 1Pootis1** [comment]
Good afternoon
ok, I will do that while I wait for your solution to this problem, thanks for the answer :)

**Comment by WolfyScript** [comment]
I looked into it. I updated the ProtocolLib dependency to 5.0.0-SNAPSHOT, but no errors occur in the code... hmm.
The method it complains about actually still exists in 5.0.0 and should work fine.
I need to further look into it and see what might cause it. 
In case there is a new ProtocolLib it might be good to try that one out.
