### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by AntsandIce** [WolfyScript/CustomCrafting#160]
### What happened?

(https://pastebin.com/KmqyD8VH) The plugin works fine, but there are errors. The errors disappear when update to 1.19.2.

### How can the bug be reproduced?

when starting the server

### Expected Behaviour?

....

### Plugin version

WolyUtilities 4.16.4.1 CustomCrafting 3.16.8.1

### Server software

purpur-1.19-1735

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
That is happening, because those recipes and items were created in 1.19.1 or 1.19.2 and cannot be used in older versions of Minecraft. But recipes and items created in older versions do work on later versions, so if you do need them to work across different versions, create them in the oldest MC version.
