### ISSUE TITLE
Crafting cooldown on elite crafting tables

### ISSUE THREAD

**Issue by AllayBreeze** [WolfyScript/CustomCrafting#164]
### The Problem

Crafting on elite crafting tables frequently causes lags. Maybe adding a cooldown can relieve this situation?

### Solution

After a successful crafting, players should wait for some time to craft again.

During the cooldown players cannot put items on the crafting slots.

A countdown can be shown below the output space.

During cooldown, crafting spaces can be filled with something, such as stained glass, to indicates it.

### Alternatives

This cooldown can also be designed during between a player put items into different crafting slots, when players put something into a crafting slot, they need to wait for several seconds/ticks to put another again.

Two kinds of cooldown can be added together, and can be enabled in common.

### Additional Context

If there's finally a way to fix the lag, this suggestion should be eliminated?

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
You might be interested to hear that the Elite Crafting Recipes can already have a Craft Delay condition.  
Of course that needs to be done on a per-recipe basis, but it should be a good alternative (for now).  

There is also no feedback for the player, I think. So that is something I could add too.  

I'll have a look into adding a complete workstation wide craft delay (or workstation conditions?... not sure).
