### ISSUE TITLE
Items get bugged away

### ISSUE THREAD

**Issue by Nononitas** [WolfyScript/CustomCrafting#200]
### What happened?

- You can glitch items away when using the recipe book
- Crafting doesn't work correctly when shift clicking on the recipe, see second video

### How can the bug be reproduced?

See here, note there are no glass panes in the recipe book 
https://youtu.be/Ke0__jBE7s8

Crafting doesn't work: Some Items dissappear
I was shift clicking on the recipe in the workbench
The default vanilla brick recipe is deactivated, I created a custom one where meta needs to match (see end of the video)
https://www.youtube.com/watch?v=dlw4OHjKBZE

### Expected Behaviour?

That items won't get gliched away

### Plugin version

WolfyUtils 4.16.9.5 and CC-free 4.16.3.2

### Server software

1.19.2 Paper

### Submit issue

- [X] read the Wiki and especially the FaQ, and made sure there is no fix to your issue,
- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Thanks for more detailed information. I saw in discord that you found a temporary fix, for the first issue, that is.   
I'll see how I can block inventory move interactions when background panes are disabled.  

Regarding the second issue.  
Do you have Protocol Lib Installed? Due to some limitations in bukkit/spigot, that plugin is required to fix this issue.
https://github.com/WolfyScript/CustomCrafting/issues/136#issuecomment-1151609414

**Comment by Nononitas** [comment]
Yes ProtocolLib is installed on the server
