### ISSUE TITLE
CurseForge installation does not work

### ISSUE THREAD

**Issue by CJ-Studios-7** [WolfyScript/CustomCrafting#240]
### The Problem

You have a CurseForge download page but you cannot use the mod on CurseForge. When you click on "Install on CurseForge app" there is an error that says Manifest file does not exist. This is likely because the mod isn't Fabric or Forge.

### Solution

Is there any way I can get the mod to work on Forge? That could be very useful for an event I am hosting.

### Alternatives

Maybe a way for the mod to work on Fabric?
Also do I need Bukkit or can I install directly into my world?

### Additional Context

I'm trying to code in a craft that creates an item that can be used to summon a final boss. Everything else is figured out but I don't know how to make it so that I can have a crafting recipe for a custom item using data packs so I turned to this. :p
![image_2023-03-14_204507507](https://user-images.githubusercontent.com/127907976/225174515-50c4b8e3-9f87-4324-9f82-94737179b27b.png)

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Not sure what the install button is doing there anyways. 
The plugin is listed on CurseForge under the Bukkit and therefor you need a Spigot (A extension of Bukkit; pure bukkit is no longer a thing) server to run it. 

There are ways to integrate the Spigot API on a Forge server, but that is currently not supported by CustomCrafting nor WolfyUtilities.
I plan to make a Sponge implementation in the future to make it work on Forge servers, but that'll still take time.

For now you are better off using an actual Forge mod to add crafting recipes. I can't tell you were to find those, but I am sure there must be mod for this. Otherwise Datapacks are a thing and have gotten a lot more powerful over the years.

**Comment by CJ-Studios-7** [comment]
Its all good I coded a custom datapack that did what I needed, but thanks anyway!
