### ISSUE TITLE
Don't clear custom enchants and custom nbt

### ISSUE THREAD

**Issue by LupusVirtute** [WolfyScript/CustomCrafting#256]
### The Problem

Right now if i add my custom enchant to item when i put it into crafting it clears some nbt values

### Solution

Dont clear any nbt values put NBT into config file as well as custom enchants

### Alternatives

Writing my own custom crafting plugin

### Additional Context

![image](https://user-images.githubusercontent.com/44524396/230713994-9bec9018-ba40-4434-a1b0-b9b425b19478.png)
![image](https://user-images.githubusercontent.com/44524396/230713999-1374e65f-3fef-42fd-bbd3-52c4ce2ce04f.png)
`

### Submit issue

- [X] searched for and ensured there isn't already an open issue regarding this,
- [X] are running the latest version of your server software (Spigot, Paper, etc.), and plugins (WolfyUtilities, CustomCrafting).

**Comment by WolfyScript** [comment]
Did you create the item using another plugin?
Like MMOItems, ItemsAdder, Oraxen, MythicMobs, ExecutableItems, or another plugin.
If you did, the plugin will detect the ID of the item in that plugin and takes the latest version of it that was saved. 

However, that means that NBT tags added to the item not within that plugin will be discarded.
I will have to do some changes to the behaviour internally, so I pushed a fix back to the next major v5 update.
But that can still take several months to be in an alpha state.

For now, you could disable (set to `false`) the feature that detects the id in the `config.yml` of **WolfyUtilities**.
```yml
api_references:
  mmoitems: true
  oraxen: true
  mythicmobs: true
  itemsadder: true
```
Make sure to stop the server before editing the config.
Be careful when disabling it, because if you use items of that plugin as ingredients, they may not function properly and may cause major performance penalties.
As long as you only use the items as result items it is fine and causes no issues, except that the items in the recipe are not automatically updated when changed in the third-party plugin.

**Comment by LupusVirtute** [comment]
I have created item using my own plugin enchanting but the item originally comes from ItemsAdder thanks for the answer it answers my question but it would be better to notify users about this
